# Shopify Theme App Extension Configuration
# https://shopify.dev/docs/api/app-extensions/theme

api_version = "2024-10"

[[extensions]]
uid = "<EXTENSION_UID>"
type = "theme"
name = "3D Product Viewer"
handle = "product-3d-viewer"

[extensions.settings]
  [[extensions.settings.blocks]]
  type = "product_3d_viewer"
  name = "3D Product Viewer"
